"""
La asignación de valores numéricos únicos a cada protocolo en el mapeo anterior es una estrategia eficaz para simplificar el análisis en modelos de aprendizaje profundo. Sin embargo, hay algunos puntos que podrían mejorarse:

Valores Únicos por Protocolo: Actualmente, algunos protocolos como "TLSv1.2", "TLSv1.1", "TLSv1.3", "TCP", y "UDP" tienen el mismo valor asignado (1). Esto podría causar confusión en el modelo, ya que no podrá diferenciar entre estos protocolos. Sería más útil asignar un valor numérico único a cada protocolo.

Consistencia con los Puertos: Algunos protocolos están asignados a sus puertos conocidos, como "HTTP" (80) y "HTTPS" (443). Si bien esto es lógico, podría causar inconsistencias en el modelo si otros protocolos comparten el mismo puerto o si un protocolo usa múltiples puertos.

Simplificación y Estandarización: Considera estandarizar todos los protocolos a una escala numérica única donde cada uno tenga un número diferente. Esto puede implicar alejarse de los números de puerto reales y, en cambio, asignar identificadores numéricos secuenciales o basados en alguna otra lógica.
"""
protocolo_numero_mapa = {

    "TLSv1.2": 1,
    "TLSv1.1": 2,
    "TLSv1.3": 3,
    "TCP": 4,
    "QUIC": 5,
    "UDP": 6,
    "HTTP": 7,
    "HTTPS": 8,
    "FTP": 9,
    "FTPS": 10,
    "SSH": 11,
    "Telnet": 12,
    "SMTP": 13,
    "DNS": 14,
    "DHCP": 15,
    "TFTP": 16,
    "HTTP-Alt": 17,
    "POP3": 18,
    "IMAP": 19,
    "LDAP": 20,
    "SMB": 21,
    "Syslog": 22,
    "Syslog-TLS": 23,
    "NTP": 24,
    "SNMP": 25,
    "SNMPTRAP": 26,
    "RDP": 27,
    "SIP": 28,
    "MQTT": 29,
    "MySQL": 30,
    "PostgreSQL": 31,
    "MSSQL": 32,
    "OracleDB": 33,
    "RADIUS": 34,
    "NetBIOS": 35,
    "RPC": 36,
    "NFS": 37,
    "VNC": 38,
    "SSDP": 39,
    "HTTP-Proxy": 40,
  "ICMPv6": 41,
  "ICMPv4": 42,
    # ... otros protocolos según sea necesario
}

protocolo_numero_mapa_port = {
  "TLSv1.2": 1,
  "TLSv1.1": 1,
  "TLSv1.3": 1,
  "TCP": 1,
  "QUIC": 443,
  "UDP": 1,
  "HTTP": 80,
  "HTTPS": 443,
  "FTP": 21,
  "FTPS": 990,
  "SSH": 22,
  "Telnet": 23,
  "SMTP": 25,
  "DNS": 53,
  "DHCP": 67,
  "TFTP": 69,
  "HTTP-Alt": 8080,
  "POP3": 110,
  "IMAP": 143,
  "LDAP": 389,
  "SMB": 445,
  "Syslog": 514,
  "Syslog-TLS": 6514,
  "NTP": 123,
  "SNMP": 161,
  "SNMPTRAP": 162,
  "RDP": 3389,
  "SIP": 5060,
  "MQTT": 1883,
  "MySQL": 3306,
  "PostgreSQL": 5432,
  "MSSQL": 1433,
  "OracleDB": 1521,
  "RADIUS": 1812,
  "NetBIOS": 137,
  "RPC": 135,
  "NFS": 2049,
  "VNC": 5900,
  "SSDP": 1900,
  "HTTP-Proxy": 8080,
}
